export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER = "USER_REGISTER";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";