export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER = "USER_REGISTER";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";

export const GET_FIXEDCOST = "GET_FIXEDCOST";
export const ADD_FIXEDCOST = "ADD_FIXEDCOST";

export const GET_MATERIALCOST = "GET_MATERIALCOST";
export const ADD_MATERIALCOST = "ADD_MATERIALCOST";